package com.boostcamp.mapisode.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class CustomColorScheme(
	val navSelectedItem: Color,
	val navUnselectedItem: Color,
	val navBackground: Color,
	val topAppBarTitle: Color,
	val scaffoldBackground: Color,
	val buttonBackground: Color,
	val buttonContent: Color,
	val buttonStroke: Color,
	val chipBackground: Color,
	val chipStroke: Color,
	val textFieldBackground: Color,
	val textFieldContent: Color,
	val textFieldStroke: Color,
	val dialogBackground: Color,
	val dialogStroke: Color,
	val dialogDismiss: Color,
	val dialogConfirm: Color,
	val toastBackground: Color,
	val toastStroke: Color,
	val toastContent: Color,
	val iconColor: Color,
	val surfaceBackground: Color,
	val dividerThinColor: Color,
	val dividerThickColor: Color,
	val textBackground: Color,
	val textContent: Color,
	val textStroke: Color,
	val fabBackground: Color,
	val fabContent: Color,
	val systemBarTransparent: Color,
	val systemBarColored: Color,
	val eatIconColor: Color,
	val seeIconColor: Color,
	val otherIconColor: Color,
)

// Light Theme Color Scheme
val lightColorScheme = CustomColorScheme(
	navSelectedItem = Primary30,
	navUnselectedItem = Neutral90,
	navBackground = Primary30,
	topAppBarTitle = Primary90,
	scaffoldBackground = Neutral10,
	buttonBackground = Primary30,
	buttonContent = Neutral10,
	buttonStroke = Color.Unspecified,
	chipBackground = Neutral20,
	chipStroke = Primary20,
	textFieldBackground = Color.Unspecified,
	textFieldContent = Neutral60,
	textFieldStroke = Neutral60,
	dialogBackground = Neutral20,
	dialogStroke = Color.Unspecified,
	dialogDismiss = Error30,
	dialogConfirm = Primary80,
	toastBackground = Neutral20,
	toastStroke = Color.Unspecified,
	toastContent = Neutral110,
	iconColor = Neutral110,
	surfaceBackground = Neutral30,
	dividerThinColor = Neutral50,
	dividerThickColor = Neutral80,
	textBackground = Color.Unspecified,
	textContent = Neutral110,
	textStroke = Color.Transparent,
	fabBackground = Primary60,
	fabContent = Primary30,
	systemBarTransparent = Color.Transparent,
	systemBarColored = Neutral20,
	eatIconColor = Tertiary10,
	seeIconColor = Error10,
	otherIconColor = Primary40,
)

// Dark Theme Color Scheme
val darkColorScheme = CustomColorScheme(
	navSelectedItem = Primary30,
	navUnselectedItem = Neutral40,
	navBackground = Primary30,
	topAppBarTitle = Primary10,
	scaffoldBackground = Neutral110,
	buttonBackground = Primary60,
	buttonContent = Neutral110,
	buttonStroke = Color.Unspecified,
	chipBackground = Neutral100,
	chipStroke = Primary70,
	textFieldBackground = Color.Unspecified,
	textFieldContent = Neutral70,
	textFieldStroke = Neutral70,
	dialogBackground = Neutral100,
	dialogStroke = Color.Unspecified,
	dialogDismiss = Error20,
	dialogConfirm = Primary20,
	toastBackground = Neutral100,
	toastStroke = Color.Unspecified,
	toastContent = Neutral10,
	iconColor = Neutral10,
	surfaceBackground = Neutral90,
	dividerThinColor = Neutral80,
	dividerThickColor = Neutral50,
	textBackground = Color.Unspecified,
	textContent = Neutral10,
	textStroke = Color.Transparent,
	fabBackground = Primary30,
	fabContent = Primary60,
	systemBarTransparent = Color.Transparent,
	systemBarColored = Neutral100,
	eatIconColor = Tertiary20,
	seeIconColor = Error40,
	otherIconColor = Primary50,
)
